### PR TITLE
Update JS dependencies

### PR DESCRIPTION
**Pull request by davidfischer**
This should fix the github JS vulns warning. I tested this by running `npm run dev` and `npm run build` to ensure that the JS still runs and compiles CSS/JS.

### CODE REVIEW

**Comment by eine** [comment]
@davidfischer, it seems that `matchdep` is not used (imported/required) anywhere. Is it an actual dependency?

**Comment by davidfischer** [comment]
I didn't actually check whether it was needed. I'll check if it is and remove it otherwise. Thanks for the tip.

**Comment by davidfischer** [comment]
It is not used. I removed it!

**Comment by eine** [comment]
Good! BTW, It would be handy to use david-dm and/or dependabot to keep dependencies up to date: [devDependencies Status](https://david-dm.org/readthedocs/sphinx_rtd_theme?type=dev)

**Pull request merged**
