### PR TITLE
Add missing dot after copyright.

### PR DESCRIPTION
**Pull request by mgeier**
The following stuff each has a dot at the end.

### CODE REVIEW

**Comment by Blendify** [comment]
This is intentional so developers have full control of the text.

**Comment by mgeier** [comment]
It's still a breaking change from the `basic` theme:

https://github.com/sphinx-doc/sphinx/blob/80d9728101ab349050a708261da623a306f09f85/sphinx/themes/basic/layout.html#L199-L205

**Comment by stsewd** [comment]
Looks this is superseded by https://github.com/readthedocs/sphinx_rtd_theme/pull/933, discussion about the final dot https://github.com/readthedocs/sphinx_rtd_theme/pull/666

**Comment by stsewd** [comment]
Closed by https://github.com/readthedocs/sphinx_rtd_theme/pull/933

**Pull request closed without merging**
