### PR TITLE
CSS: Add overflow-wrap to links inside paragraphs

### PR DESCRIPTION
**Pull request by nienn**
### Problem

Long links are not wrapping and are either triggering the body horizontal scrollbar or overflowing outside the document.

### Changes

Adds the following styles
```css
.rst-content p a {
    overflow-wrap: anywhere
}
```

### CODE REVIEW

**Review by benjaoming — COMMENTED** [review]
LGTM - I can rebuild the CSS and add a regression test.

**Comment by benjaoming** [comment]
Change looks good! Added a new visual regression test:

image

**Review by benjaoming — APPROVED** [review]
Did some manual checking and building, LGTM :+1:

**Comment by dolfinus** [comment]
This change caused issue #1368

**Pull request merged**
