### PR TITLE
Show version for Sphinx and this template in footer.

### LINKED ISSUE #1327: Some translation issues
Hi I am a translator of zh_CN. Here are some issues about the translation.

1. Merge these three strings into one.
https://github.com/readthedocs/sphinx_rtd_theme/blob/b553aa6626d4910b581acb179f93defcb6a5a1c8/sphinx_rtd_theme/footer.html#L50-L57
image
This sentence is currently separated into 3 strings in Transifex. It is inconvenient for some languages while translating because the sequence of words is not completely the same as English in some languages. I hope it could correspond to one string in Transifex.

2. [Obsolete entries(strings)](https://github.com/readthedocs/sphinx_rtd_theme/blob/b553aa6626d4910b581acb179f93defcb6a5a1c8/sphinx_rtd_theme/locale/en/LC_MESSAGES/sphinx.po#L184-L200) are still parsed in Transifex. Not sure if this issue is related to Transifex itself.
image

BTW, I want to improve the zh_CN translation. But some strings I want to change are marked as reviewed in Transifex. Who can I find to help me cancel that reviewed state in Transifex?

### PR DESCRIPTION
**Pull request by marxin**
Let's continue here where we ended in #1269.

@benjaoming edit:
Fixes #1327

### CODE REVIEW

**Comment by benjaoming** [comment]
Great, thanks for following up @marxin :+1: 

Before making adjustments in the PR, I want to hear from @agjohnson if he's fine with adjusting the text of the footer as well.

> Built with Sphinx 6.1.3 using sphinx-rtd-theme 1.2.0rc2 by Read the Docs. 

Looks like:

image

Motivation: The version string looks odd next to "a theme", I think it's because it's very specific to mention the theme version but not its name. This is also shorter.

It should be clear from the name "sphinx-rtd-theme" that it's a theme :)

**Comment by benjaoming** [comment]
@marxin do you mind if I make some modifications in this PR?

While going over https://github.com/readthedocs/sphinx_rtd_theme/issues/1327, I realized that we are modifying exactly the same text and perhaps we should fix that issue in the same go. It's about merging the 3 separate strings into one big string for translation.

**Comment by marxin** [comment]
> @marxin do you mind if I make some modifications in this PR?

Go ahead! I'm fine with that.

**Comment by marxin** [comment]
@benjaoming: May I please remind you this PR?

**Comment by benjaoming** [comment]
Looking good! Now as a single translation string:

image

**Comment by marxin** [comment]
Can you please merge it now?

**Comment by Geeyun-JY3** [comment]
Why this PR is closed?

**Comment by marxin** [comment]
I'm sorry, but the pull request is quite stalled and I've lost interest in the meantime.
Feel free to re-open it in a separate PR.

**Comment by Geeyun-JY3** [comment]
Fine :(

**Pull request closed without merging**
