### PR TITLE
Fix rendering of footnotes and citations for Sphinx 2

### LINKED ISSUE #741: Footnotes not rendering like the demo in Sphinx 2.0
### Problem

Footnotes do not render like they do in the demo.

### Reproducible Project

- I copied and pasted the RST from the demo itself.
- I am not running any custom CSS.
- I have enabled the following extension
	```python
	extensions = [
    	"sphinx.ext.autodoc",
    	"sphinx.ext.doctest",
    	"sphinx.ext.intersphinx",
    	"sphinx.ext.todo",
    	"sphinx.ext.coverage",
    	"sphinx.ext.mathjax",
    	"sphinx.ext.ifconfig",
    	"sphinx.ext.viewcode",
    	"sphinx.ext.githubpages",
    	"sphinx.ext.napoleon",
    	"sphinx.ext.autosummary",
    	"sphinx.ext.inheritance_diagram",
    	"sphinx.ext.graphviz",
	]
	```
- I have the following `sphinx_rtd_theme` configuration:
	```python
	html_theme_options = {
    	"display_version": True,
    	"sticky_navigation": True,
    	"collapse_navigation": False,
    	"navigation_depth": 4,
	}
	```
##### Note

This issue can be reproduced easily by using Cookiecutter with the "New Python Package" template, preparing a `virtualenv` with `sphinx` and `sphinx_rtd_theme`, changing the default to RTD and making the docs after copying the demo RST to one of the default .rst files that come with the template.

#### Error Logs/Results

Erroneous Style

#### Expected Results

Display footnotes as they do in the demo.

aragraph Level Markup — Read the Docs Sphinx Theme 0.4.3 documentation

### Environment Info

- Python Version: 3.7.1
- Sphinx Version: 2.0.0
- RTD Theme Version: 0.4.3

### PR DESCRIPTION
**Pull request by jessetan**
Sphinx 2 uses definition lists for footnotes and citations instead of tables, yay!
The existing theme CSS undid most of the default styling wyrm applied to tables so footnotes looked better. I've added similar styles for Sphinx 2. The rendering for Sphinx < 2 is unaffected.

There are minor visual differences, review is appreciated.

Sphinx <2:
Screen Shot 2019-07-19 at 15 02 36

Sphinx >2:
Screen Shot 2019-07-19 at 15 26 05

Differences:

- back references (the `(1,2)` links) are not aligned with the footnote text due to different DOM structure. I do not consider this an issue
- Footnote text does not start on same line as label. This is less compact and I'm not sure it takes up too much space. It is also harder to fix nicely with a consistent look for footnotes with and without a back reference. Note the inconsistency between footnote 1 and 2 in the previous situation

Fixes #741

### CODE REVIEW

**Comment by agjohnson** [comment]
I took a different approach with this, using flex:

image

However, it's flex, which is not a great application for converting lists into tables. But it's not playing around with floats at least. Is the tabular display of footnotes something worth preserving?

One area that it doesn't look correct, because it's sized proportionally:

image

**Comment by rkwestel** [comment]
Is there a reason footnotes were changed from tables to definition lists? Even if you change the styling via CSS to get rid of the ugly background and border, short of jumping through flex hoops as @agjohnson shows, you're still stuck with the disconnected presentation of a footnote number with its associated content on the next line; it looks terrible and takes up way more space than necessary. This provokes my distaste for markup languages that presume to know what you want and often get it wrong.

**Comment by agjohnson** [comment]
Sphinx 2 uses it's HTML 5 writer by default, which outputs definition lists. Sphinx < 2 uses the HTML 4 writer by default, which is a table.

**Comment by polyzen** [comment]
Perhaps this is a regression or they have a good reason for this.

**Comment by rkwestel** [comment]
> Perhaps this is a regression or they have a good reason for this.

Perhaps, but I fail to see one. I'm advocating for dropping the use of footnotes altogether, or hand-coding them with embedded html, which defeats the purpose of markup to begin with. <insert "disappointed" emoji here>

**Comment by rkwestel** [comment]
On a positive note, I just found this and will try the various suggestions until I find one that works for us: https://stackoverflow.com/questions/1713048/how-to-style-dt-and-dd-so-they-are-on-the-same-line/21261303#21261303

**Comment by agjohnson** [comment]
That is the ideal CSS fix, however `grid-column-start` is not supported by the browsers that we support, it's a relatively new feature.

I think that the most compatible way that we can address this is to override the writer being used by the builder and output a more helpful structure. For now, a fix like this PR presents the least number of issues and doesn't harshly affect display.

**Comment by jessetan** [comment]
> Is the tabular display of footnotes something worth preserving?

@agjohnson I would be OK with dropping the tabular (it's what sphinx does after all), hence my PR. Floats and flex have the annoying habit to produce corner cases that look completely off.

**Comment by Blendify** [comment]
> That is the ideal CSS fix, however `grid-column-start` is not supported by the browsers that we support, it's a relatively new feature.
> 
> I think that the most compatible way that we can address this is to override the writer being used by the builder and output a more helpful structure. For now, a fix like this PR presents the least number of issues and doesn't harshly affect display.

@agjohnson do you approve this PR?

**Comment by agjohnson** [comment]
I think I've come around to CSS `grid`. While flex worked, there were edge cases that I hit. The fallback from CSS grid looks similar to the results above, so it would be mostly safe.

The fixes are in #838, which supersedes the need for this PR

**Comment by Blendify** [comment]
I think we can agree on using #838 as a proper fix here.

**Pull request closed without merging**
