### PR TITLE
Release 1.1.0b1 + 1.1.0b2 (bump versions with bump2version)

### PR DESCRIPTION
**Pull request by benjaoming**
Refs: #1309 

@agjohnson it seems that bump2version reformats setup.cfg -- we are perhaps using this for the first time since last release. I think it looks fine.

Once this PR is approved, I would complete these items:

1. [ ] Release on PyPy
2. [ ] Tag the released commit
3. [ ] Merge PR

I'm not - however - entirely sure of the tagging process since the `bumpversion` section in setup.cfg also seems to want a `tag` and `commit` value, creating a bit of chicken/egg situation.

Maybe that's not too important now, but I'd like to go over the entire release process for 1.2, splitting it up in a preparation check list (I like things that can be copy-pasted into issues or PRs) and a PyPi+version bumping section.

### CODE REVIEW

**Review by agjohnson — APPROVED** [review]
This looks correct :+1:

However, I don't remember bump2version reformatting setup.cfg. It should just be doing a string replacement :shrug: 

bumpver does not do this though, and we've settled on using that instead anyways. We can deal with that some point in the future though.

**Comment by benjaoming** [comment]
> However, I don't remember bump2version reformatting setup.cfg. It should just be doing a string replacement

We migrated a lot of package properties from setup.py to setup.cfg, not sure if that's related.. bump2version wants to store data in setup.cfg, so most likely it parses and rewrites the file. Possibly it's because of that... or maybe my local ini parser :shrug: I found an issue about bump2version that indicated that setup.cfg support was added later, so maybe it's not fully mature. I think we should do the pyproject.toml thing eventually, so I can definitely live with this :)

**Comment by benjaoming** [comment]
@agjohnson I think I got the "alpha1" prefix from package.json, but looking at previous releases, we do align with PEP440, so I think we should continue like that. I also bumped to "b1" instead.

**Comment by benjaoming** [comment]
Pardons. The first 1.1.0b1 release will have to go down as a mistake, I hadn't merged master into the release branch with latest changes.

Merging and rebuilding assets.

**Comment by benjaoming** [comment]
Merging because released :+1:

**Pull request merged**
