### PR TITLE
Remove Modernizr

### PR DESCRIPTION
**Pull request by jessetan**
# DO NOT MERGE YET

This PR removes Modernizr, as discussed in #525.
Behavior of non-evergreen browsers (mainly IE6 - IE11) needs to be verified, as this also removes the html5shiv that is incorporated in Modernizr. Possible effects may be incorrect rendering, buttons not working, navigation not functioning, JavaScript errors in console

This PR does not remove the rAF polyfill for old IE.

- [x] Chrome (latest) verified
- [x] Firefox (latest) verified
- [x] Edge (latest) verified
- [x] IE11 verified
- [ ] IE10 verified
- [ ] IE9 verified
- [ ] IE8 verified
- [ ] IE7 verified
- [ ] IE6 verified

### CODE REVIEW

**Comment by mitya57** [comment]
Microsoft has a great service for generating website screenshots with different browsers, including all IE versions since IE 8:

https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/

If you deploy your changes somewhere, it will be quite easy to see which browsers get broken.

**Comment by jessetan** [comment]
I know of that page (I even referenced it in the comment above) but it seems to produce some different results from actual tests on browsers. Since I don't know exactly how they are creating the screenshots, I prefer manual testing for such an important change.
Screenshots also don't show JS errors, scrolling behavior, click behavior etc.

**Comment by mitya57** [comment]
Oh, how could I not notice that link :)

**Comment by jessetan** [comment]
@rupl thanks for commenting. I'm not sure how applicable your comment is, since sphinx_rtd_theme is not a Drupal theme, but a Sphinx theme.

**Comment by rupl** [comment]
looooool sorry 😳

**Comment by Blendify** [comment]
I think we should go forward with this.

**Comment by jessetan** [comment]
Closing in favor of #756

**Pull request closed without merging**
