### PR TITLE
raise docutils version bound

### LINKED ISSUE #1557: Support for docutils 0.21
Release notes: https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-21-2024-04-09

### PR DESCRIPTION
**Pull request by alex**
fixes #1557

### CODE REVIEW

**Comment by alex** [comment]
Is there anything I can do to help move this forward?

**Comment by stsewd** [comment]
We may need to do some visual testing, I think we did that in the past (cc @agjohnson).

From the changelog I see some entries of interest:

- Stop setting the "footnote-reference" class value for footnote references. Use the CSS selector `[role="doc-noteref"]` (works since Docutils 0.18, see minimal.css for examples).
- Embed SVG images as <svg> instead of data-URI.

**Comment by alex** [comment]
Tests failing because of Sphinx 8.

**Comment by humitos** [comment]
We released a new version [`3.0.0rc1`](https://pypi.org/project/sphinx-rtd-theme/3.0.0rc1/) that adds support for latest docutils versions. Please, give it a try and open an issue for any problem or feedback you want to share with us.

**Pull request closed without merging**
