### PR TITLE
Bump docutils to include 0.19

### PR DESCRIPTION
**Pull request by phlax**
Signed-off-by: Ryan Northey <ryan@synca.io>

### CODE REVIEW

**Comment by phlax** [comment]
apologies opened in error

**Comment by benjaoming** [comment]
NP :+1: Does docutils 0.19 work well for you?

**Comment by phlax** [comment]
> Does docutils 0.19 work well for you?

i didnt get so far as properly testing yet - it got rid of the invalid escape errors i was hitting with 0.18, and ci tests pass, but i didnt run a build - i can report back here as i do

**Comment by benjaoming** [comment]
Thanks, it's great with feedback! What is the reason that you cannot use 0.18? Is that some bug in docutils 0.18 that's fixed in 0.19 or a dependency that isn't compatible?

**Comment by phlax** [comment]
> Thanks, it's great with feedback! What is the reason that you cannot use 0.18? Is that some bug in docutils 0.18 that's fixed in 0.19 or a dependency that isn't compatible?

my motivation was 2-fold 

- i was immediately hitting invalid escape errors with 0.18 and didnt see any obvious solution
- wanting to be able to use the latest sphinx versions

reading through tickets it seemed like the pin is there more for backward compatibility - so it seemed like worth the effort to try running the newer version

**Comment by benjaoming** [comment]
Sounds good! The reason that it's not supported in the sphinx_rtd_theme is because so many documentation projects are built without upper bounds on dependencies, so it's too risky to open for docutils 0.19 until it's well-tested. All feedback is appreciated :+1:

**Comment by phlax** [comment]
So with updated/contrived deps:

```requirements
sphinx>=6.1.3
docutils~=0.19.0
sphinx-rtd-theme @ https://github.com/phlax/sphinx_rtd_theme/archive/11a587c63fd2237003e60a7359e8503c7ea094a1.zip#egg=sphinx_rtd_theme
sphinx-tabs @ https://github.com/phlax/sphinx-tabs/archive/338fda565dbf917650503b3cf0d35760f7fe07df.zip#egg=sphinx-tabs
```

all seems to be good - ci passes, no escape issues, and docs build

visually, clicky testing the built docs, im not seeing any differences - not sure exactly what to look for - we had issues with tabs <> docutils in the past - but all looks good 

the only issue im hitting with some custom jquery-based code - but i think that is just a regular upgrade type issue

**Comment by phlax** [comment]
just following up on above - i do actually hit an issue with sphinx==6.1.3 - altho i think unrelated to either the theme or docutils

sphinx ticket is https://github.com/sphinx-doc/sphinx/issues/11163

**Comment by benjaoming** [comment]
> the only issue im hitting with some custom jquery-based code

sphinxcontrib-jquery is a dependency of sphinx-rtd-theme and should ensure that jquery is loaded. However, as you can find in #1421, it doesn't get loaded on local builds.

**Pull request closed without merging**
