### PR TITLE
Added aria-label to search box input field.

### LINKED ISSUE #1379: Missing label on search form
### Problem

The search form doesn't have a required label. This is an accessibility issue, "a form control does not have a properly associated text label, the function or purpose of that form control may not be presented to screen reader users."

### Reproducible Project

You can see the error reported by the Wave tool: https://wave.webaim.org/report#/https://sphinx-rtd-theme.readthedocs.io/en/stable/.

#### Error Logs/Results

Wave error report

#### Expected Results

Use `aria-label` to add the missing label. See https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html for examples. I will submit a pull request when I can.

### PR DESCRIPTION
**Pull request by dmundra**
Fixes #1379

### CODE REVIEW

**Review by benjaoming — APPROVED** [review]
This change is great, thank you for fixing an accessibility issue. The readily existing translation is reused. Looks good to go :+1:

**Comment by benjaoming** [comment]
I'm going to try to build this again. Not sure about what to make of the previous build error since Pull Request Builds are enabled and we have an Open Source plan for this repo.

**Comment by agjohnson** [comment]
I reached out to CircleCI support on this one. I think they are expecting contributors to sign in and authorize CircleCI to run checks for PRs here, which is very wrong. I'm guessing the forked repository base doesn't help here, but this was never a problem before they changed their pricing.

**Comment by benjaoming** [comment]
Merging this smaller change, it has another approval here: https://github.com/readthedocs/sphinx_rtd_theme/issues/1379#issuecomment-1317224192

**Comment by benjaoming** [comment]
Btw thanks for fixing this @dmundra :clap: 

Direct contributions and accessibility insights always most welcome :+1:

**Pull request merged**
