### PR TITLE
Deprecate html4_writer

### LINKED ISSUE #938: Deprecate HTML4 writer
The 0.5.0 release is dealing with a lot of incompatibility added by Sphinx switching the default html writer to HTML5. While we can continue supporting both the html4 and html5 writer in our stylesheets, we will be duplicating development efforts and QA on any stylesheet changes that touch list styles or other elements that were significantly altered with the switch to the HTML5 writer.

The issue that I'm seeing with supporting the html4 writer is that we'll have spread testing and QA of the theme pretty thin, as we already have to support 3 versions of Sphinx and multiple versions of Python. Adding on top of this testing of both html4 and html5 writer for at least multiple versions of Sphinx feels like a lot of testing for little benefit.

So: what are our feelings on the HTML4 writer? Is it important to support it? This is almost a conversation about which versions of Sphinx we want to support, as I think most users just use the default version of the writer.

I think what I'd propose is:

* Aim to support Sphinx 2.0 and 3.0 with a 1.0 release. Do we not support Sphinx 1.8 at all?
* Start throwing a soft deprecation warning about the html4 writer. Users using Sphinx<2.0 will likely see this warning. The deprecation warning will alert the user to switch to a newer release of Sphinx or the HTML5 writer
* In a following release, 2.0 perhaps, we throw a harder deprecation warning or error if using the HTML4 writer. In this release, I guess we remove the HTML4 writer specific CSS rules.

### PR DESCRIPTION
**Pull request by Blendify**
This does not remove the fixes that we made for the html4_writer, these could be removed in a future release.

Depends on #1075
Fixes #938

### CODE REVIEW

**Comment by Blendify** [comment]
image

**Comment by agjohnson** [comment]
Also going to block this PR. It might make more sense to put this in a release before removing Sphinx 2 support. Currently, we have not described to users that it's required to upgrade to the HTML5 writer, so jumping right to breaking builds will be a bad experience for users.

**Comment by Blendify** [comment]
Note, this does not break builds using the html4 writer this might not require sphinx2, I am a bit unsure if sphinx will work if we evaluate a config value which is not present.

**Comment by Blendify** [comment]
Closing in favor of 114fb85b441db180af2f53dc0f74f16bf7c72e16

**Pull request closed without merging**
