### PR TITLE
Require Sphinx2

### LINKED ISSUE #679: Fix conditional logic around search include for Sphinx 1.8
The logic introduced in #672 could stand to be a bit more defensive -- a tuple comparison or something similar would be great.

### PR DESCRIPTION
**Pull request by Blendify**
We now depend on the html5 builder and we want to deprecate the html4 writer see: #938. A printed warning message will come in a different PR. Before this can happen, we have to ensure that the html5 writer is available which was added in sphinx2.

This patch also drops python2 and python versions less than 3.5. Sphinx2 requires these so it is safe to remove support.

Fixes #679

### CODE REVIEW

**Review by stsewd — COMMENTED** [review]
We may need to hold on this, there is a discussion about our tool support policy to be done, see https://github.com/readthedocs/readthedocs.org/pull/7859

**Comment by Blendify** [comment]
That should not affect this because readthedocs.org uses the latest version of each, this only affects if a user pins an old version of sphinx against a new version of them

**Comment by agjohnson** [comment]
We do need to hold off on this until we come up with a plan for deprecation and backwards incompatible changes across the next few versions. Going to set this one to block and put it on a future milestone.

In particular, this could break a good number of documentation builds, anywhere where users are using an old Sphinx and an unpinned theme. This will require some more thought and perhaps application logic.

**Comment by Blendify** [comment]
> We do need to hold off on this until we come up with a plan for deprecation and backwards incompatible changes across the next few versions. Going to set this one to block and put it on a future milestone.
> 
> In particular, this could break a good number of documentation builds, anywhere where users are using an old Sphinx and an unpinned theme. This will require some more thought and perhaps application logic.

The theme will now install sphinx2 if sphinx2 is not found, so I do not think that this will break any builds.
I am still undecided as to what version this should go in, this should go in before we remove support for html4 (remove html4 styling) so if version 1.0.0 should remove html4 support then it makes sense to include this change in the next point release. On the other hand, jumping to html5 by default is still a major change a can warrant to be included in 1.0.0.

**Comment by agjohnson** [comment]
This is effectively dropping Python 2.7 support. While not technically wrong, this potentially affects a large number of users. I don't have the number of builds using python2.7 still on RTD, but it was still a large number fairly recently. Anyone not pinning the theme release would end up with broken builds, which we want to avoid.

This PR might require more work, perhaps there is a packaging mechanism we can use to point python2 users to a supported version of the theme and avoid this scenario.

Otherwise, we probably don't want this change until we also take on html4 writer depreciation and bootstrap support in a release. If we merge this early, that will be the final release available to python2 users and any changes in between now and a bootstrap release would be unusable. It would be a better experience for these users to delay this change as long as possible, especially if we're not gaining anything in particular with the upgrade.

We should also release a deprecation warning now on dropping Sphinx <2 support.

**Pull request closed without merging**
