### PR TITLE
Use canonical URL from html_baseurl

### PR DESCRIPTION
**Pull request by stsewd**
This is in sphinx itself now https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_baseurl,
https://github.com/sphinx-doc/sphinx/blob/e886cc21710e23bc53af83d011131828b1020848/sphinx/themes/basic/layout.html#L135-L137

I was thinking in deprecate this at first, but the change is simple enough to migrate.

### CODE REVIEW

**Comment by ericholscher** [comment]
We should at least be alerting the user, how are they supposed to know that something has changed and their canonical URL is now broken?

**Comment by stsewd** [comment]
I think we are aiming 1.0 here soon? If not, I think we add a warning is `canonical_url` is defined.

**Review by ericholscher — CHANGES_REQUESTED** [review]
I'm -1 on this change without a deprecation path. We can't just remove features without warning users and shipping a version that works and has a warning.

**Review by ericholscher — APPROVED** [review]
This looks better 👍

**Pull request merged**
