### PR TITLE
Remove version logic on sphinxcontrib-jquery, require >=4,<5

### PR DESCRIPTION
**Pull request by benjaoming**
We had a hotfix for sphinxcontrib-jquery in place that allows for newer versions to enter the arena.

It was in anticipation of this: https://github.com/sphinx-contrib/jquery/pull/14

In addition to bumping the lower bound, I'm suggesting to add an upper bound as well so we don't have a distant future where sphinxcontrib-jquery suddenly breaks everything :)

Seeing that the package is pretty feature complete (as in: very few features is good), and hasn't received lots more of attention, it seems reasonable to expect that the 4.x series is a good one :) (FYI @AA-Turner)

### CODE REVIEW

**Comment by benjaoming** [comment]
This PR reproduces the error described [here](https://github.com/readthedocs/readthedocs.org/issues/8323#issuecomment-1471422635)

jquery.js has suddenly become the LAST script to be injected.

https://sphinx-rtd-theme--1446.org.readthedocs.build/en/1446/
vs
https://sphinx-rtd-theme.readthedocs.io/en/stable/

Why :exploding_head:

**Comment by AA-Turner** [comment]
From the logs:

```
ERROR:   py37-sphinx17: could not install deps [., readthedocs-sphinx-ext, pytest, Sphinx>=1.7,<1.8, docutils<0.18, Jinja2<3.1]; v = InvocationError("/home/circleci/project/.tox/py37-sphinx17/bin/python -m pip install . readthedocs-sphinx-ext pytest 'Sphinx>=1.7,<1.8' 'docutils<0.18' 'Jinja2<3.1'", 1)
```

You likely need to update your configuration to exclude `Sphinx<1.8` from testing alongside `sphinxcontrib-jquery>=4`.

A

**Comment by benjaoming** [comment]
@agjohnson something has changed in sphinxcontrib-jquery 4.x, meaning that we should drop Sphinx 1.7 support

This is why tox envs are currently failing.

Sounds fine for a 1.3.0 release, right?

```
ERROR: Cannot install Sphinx<1.8 and >=1.7, sphinx-rtd-theme and sphinx-rtd-theme==1.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Sphinx<1.8 and >=1.7
    sphinx-rtd-theme 1.2.1 depends on sphinx<7 and >=1.6
    sphinxcontrib-jquery 4.1 depends on Sphinx>=1.8
    The user requested Sphinx<1.8 and >=1.7
    sphinx-rtd-theme 1.2.1 depends on sphinx<7 and >=1.6
    sphinxcontrib-jquery 4.0 depends on Sphinx>=1.8
```

**Comment by benjaoming** [comment]
This is now released in `sphinx-rtd-theme==1.2.2`

**Pull request merged**
