### PR TITLE
Label tag to conform with WAVE accessibility

### PR DESCRIPTION
**Pull request by eglerean**
Adding a <label> tag to conform with https://wave.webaim.org/ WAVE accessibility tool. For more details on this webaim requirement, see https://webaim.org/standards/wcag/checklist#sc2.4.6

This pull requests is a possible solution to issue #970

### CODE REVIEW

**Comment by stsewd** [comment]
I'm just attaching a screenshot of how this looks like.

Screenshot_2020-10-26 Read the Docs Sphinx Theme — Read the Docs Sphinx Theme 0 5 0 documentation

**Comment by Holzhaus** [comment]
Is this to improve screenreader support? If so, could that label just be hidden using CSS?

**Comment by stsewd** [comment]
I think is better if we copy the upstream changes https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/themes/basic/searchbox.html looks like they have aria labels for search already. Let me know if that works

**Comment by stsewd** [comment]
Created https://github.com/readthedocs/sphinx_rtd_theme/pull/1024

**Pull request closed without merging**
