### PR TITLE
Update translations

### LINKED ISSUE #890: Pull new translations from Transifex
### Problem

Transifex has 100% complete translations for some locales which have yet to be synced into this repository and deployed in a release:

- https://www.transifex.com/readthedocs/sphinx-rtd-theme/
- https://github.com/readthedocs/sphinx_rtd_theme/tree/master/sphinx_rtd_theme/locale

Missing locales from Tx seem to be:
- fr
- pt_BR
- tr
- zh_CN

If there's interest I can likely mobilize some translators to add other locales on Transifex too, at least the ones matching the most advanced locales from the Godot docs: https://hosted.weblate.org/projects/godot-engine/godot-docs/ (ja, ko, pl, uk)

### PR DESCRIPTION
**Pull request by agjohnson**
Periodic update of translations from transifex.

Fixes #890

### CODE REVIEW

**Comment by agjohnson** [comment]
I accepted translations in Transifex for anything that vaguely translated correctly with Google translate. If there are any issues with the translations, hopefully having more eyes on the translation will help.

**Comment by macagua** [comment]
@agjohnson I done the all updating the Spanish translation On Transifex :+1:

**Comment by ericholscher** [comment]
@agjohnson would be good to grab the spanish translation before merging 👍

**Comment by agjohnson** [comment]
Yup. Will repull before release.

**Comment by agjohnson** [comment]
I also noticed that transifex is giving us all of the unreviewed string too, which seems bad. I'm going to repull without those. There is also a complete SV translation to bring in.

**Comment by agjohnson** [comment]
In #911, I updated some of the transifex command usage. It now works as expected and the translations included here only represent reviewed strings. I've rebased and regenerated everything from scratch with those changes.

My process for reviewing was performing a reverse google translate on all of the strings and looking for vague matches. I can't guarantee any of the translations unfortunately, we need more team members to get native review. I did add some context to the strings to reduce some of the confusion of terms we had.

**Comment by agjohnson** [comment]
Merged, as I don't think there is much review to do here beyond approval of updating translations.

**Pull request merged**
