### PR TITLE
Fix SASS syntax errors from #967

### PR DESCRIPTION
**Pull request by agjohnson**
This introduced syntax errors that were not picked up in review, the
`:not()` psuedo selector can't lead a selector in SASS.

Based on top of #1314, merge that first.

### CODE REVIEW

**Comment by agjohnson** [comment]
Annnd these CI failures are from the broken Jinja release, I won't fix those in this PR. This PR was only addressing the `ci/circleci:build` failures.

**Comment by benjaoming** [comment]
FYI, this was already on my radar :) https://github.com/readthedocs/sphinx_rtd_theme/pull/1312/commits/5d8fbbaf65a2ac15bd4870fb50a73c6289f26a1d

**Comment by agjohnson** [comment]
Sure, but any reason that needs to be in such a large PR? Seems we could merge a few of these and isolate your PR to add a docker development environment.

**Comment by benjaoming** [comment]
> Sure, but any reason that needs to be in such a large PR?

Nothing more or less than builds not working, so kind of hard as a new contributor to reach the bar of :heavy_check_mark:

**Pull request merged**
