### PR TITLE
Prepare for 3.0 release

### LINKED ISSUE #1557: Support for docutils 0.21
Release notes: https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-21-2024-04-09

### LINKED ISSUE #1570: Outdated docutils dependendancy
### Problem

GitHub dependabot demands docutils==0.21.2 but 'sphinx' and 'sphinx-rtd-theme' require outdated versions.
Using docutils<=0.21.2 does not make dependabot happy.

Give details on your issue.

Can you update the docutils dependency to unravel this dependency issue?

### Reproducible Project

See https://github.com/sjfke/nonbleedingedge/  (https://nonbleedingedge.com/)

$ cat requirements.txt
alabaster==0.7.16
Babel==2.15.0
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
docutils==0.21.2
idna==3.7
imagesize==1.4.1
importlib_metadata==8.0.0
Jinja2==3.1.4
MarkupSafe==2.1.5
packaging==24.1
Pygments==2.18.0
pyparsing==3.1.2
pytz==2024.1
requests==2.32.3
setuptools==70.3.0
snowballstemmer==2.2.0
Sphinx==7.3.7
sphinx-intl==2.2.0
sphinx-rtd-theme==2.0.0
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
sphinxemoji==0.3.1
urllib3==2.2.2
zipp==3.19.2

$ pip install -r requirements.txt --upgrade

#### Error Logs/Results

The conflict is caused by:
    The user requested docutils==0.21.2
    sphinx 7.3.7 depends on docutils<0.22 and >=0.18.1
    sphinx-rtd-theme 2.0.0 depends on docutils<0.21
    The user requested docutils==0.21.2
    sphinx 7.3.7 depends on docutils<0.22 and >=0.18.1
    sphinx-rtd-theme 2.0.0 depends on docutils<0.21

#### Expected Results

No errors

### Environment Info

- Python Version: Python 3.12.4 (From Microsoft Store)
- Sphinx Version: 7.3.7
- RTD Theme Version: 2.0.0

### LINKED ISSUE #1582: Support Sphinx 8
Sphinx 8 was released on July 29, yet sphinx-rtd-theme requires a Sphinx version less than 8.  Please add support for Sphinx 8.

### PR DESCRIPTION
**Pull request by humitos**
This PR prepares the theme for the 3.0 release as planned in https://sphinx-rtd-theme.readthedocs.io/en/stable/development.html#roadmap-release-3-0-0

Related PRs I'd like to include here as well:

- https://github.com/readthedocs/sphinx_rtd_theme/pull/450
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1106
- https://github.com/readthedocs/sphinx_rtd_theme/issues/1578
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1580
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1581
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1589
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1595

Closes #1570
Closes #1582 
Closes #1559
Closes #1557

### CODE REVIEW

**Comment by alex** [comment]
Sphinx 8 was just released, it probably makes sense to try to include support for that here (assuming it's not an unreasonable amount of work).

**Comment by zaufi** [comment]
> Sphinx 8 was just released…

And 2.0.0 version has a problem w/ it: #1571

**Comment by humitos** [comment]
> [Remove 'extra_css_files' #450](https://github.com/readthedocs/sphinx_rtd_theme/pull/450)

We should include a deprecation warning in 3.0, so we can remove it in 4.0 (from https://github.com/readthedocs/sphinx_rtd_theme/pull/450#issuecomment-1815040170). I agree with that 👍🏼

**Comment by humitos** [comment]
I did some QA here using `master` branch _and_ this PR.

1. Build from `master`
    ```
    tox -e "py310-sphinx{62,72,latest,dev}"
    ```
1. Build from this PR
    ```
    tox -e "py310-sphinx{62,72,latest,dev}-qa"
    ```
1. Open `firefox` and check for differences
    ```
    firefox .tox/py310-sphinx72/tmp/html/demo/demo.html
    firefox .tox/py310-sphinx72-qa/tmp/html/demo/demo.html
    ```
1. Take a look at directory diff
    ```
    diff -u .tox/py310-sphinx72/tmp/html/ .tox/py310-sphinx72-qa/tmp/html/
    ```

I haven't find any difference here, so I think we are good to go 👍🏼 

After that, I switch to this PR in particular and run `tox -e "py310-sphinx{62,74,80,latest,dev}"` to find out differences between these versions but I found nothing. I'd say we are ready to move forward with a `3.0rc1` release after doing 2.1.0rc2 (see #1580)

**Comment by humitos** [comment]
I added a few extra commits to update the docs and add some deprecation warnings 👍🏼

**Comment by agjohnson** [comment]
Also, you don't mention this above, but if you aren't already you should also test multiple browsers and also test for tablet/mobile viewport. Chromium is fairly compatible with Firefox these days, Webkit usually gives the most unexpected results. Mobile and tablet viewport sizes mostly affect elements that require positioning, like footnotes, sidebar, and tables.

**Comment by humitos** [comment]
> test multiple browsers and also test for tablet/mobile viewport

I did this and there are some differences. Depending on the "Dimensions" and "Rotation" it renders _better_ in the old or new versions --but also it seems they are fixed in Sphinx 8.x (or even in the development branch) because I'm not able to reproduce them there. I think we can make a more extensive QA here as we go and open specific issues. I haven't found anything completely broken, tho, so I don't want to block moving forward with a release that supports Sphinx 8.x because of this.

I will merge this PR and release a 3.0.0rc1 so users can start using/testing it and report specific issues we can work on.

Currently, Sphinx 8.x users are getting 0.5.x version of the theme which is worse than that the current one -- even with this small issues on tablet/mobile issues.

**Comment by alex** [comment]
Great to hear @humitos , thanks!

**Comment by agjohnson** [comment]
@humitos Could you note the differences in an issue? We should follow up on these after an RC is out.

Styling does not frequently break completely, normally differences in docutils releases (and sometimes Sphinx) causes either changes in spacing, sizing, or positioning. Sometimes entire structures have changed (footnotes) and rendering is completely different.

**Pull request merged**
