### PR TITLE
Fixes #289: Inconsistent table typography sizing

### LINKED ISSUE #289: Table cells with multiple paragraphs gets wrong formatting
table/tr/td elements gets font-size:90%, /table/tr/td/p elements does not.

### PR DESCRIPTION
**Pull request by nienn**
This tries to fix inconsistent font sizing in paragraphs (`p`) and lists (`ul`) elements inside tables.

Fixes: #289

_Note: There has been several attempts of solving this same issue across similar styles over the last few years and the CSS rules for elements inside tables are getting a bit messy. It might be useful to tidy up a bit on a future PR._

### CODE REVIEW

**Comment by benjaoming** [comment]
It would seem that in order to get this PR in, we need to merge latest master and then rebuild assets. I'll be getting a dev env up and hopefully I can push that easily after that :crossed_fingers:

@nienn looking forwards to merging this and possibly saying hi some day :wave:

**Review by benjaoming — APPROVED** [review]
Added a demo example and it looks like the font issue has gone away. I'm sure the missing margin between paragraphs inside tables would have nothing to do with this PR - proposing a follow-up issue for this. 

image

**Comment by benjaoming** [comment]
Not related to this change: Noting for a follow-up issue that the missing rules for paragraph line height and margins makes adding inline code mis-align pretty badly in the example.

image

**Review by agjohnson — APPROVED** [review]
Output looks good!

**Pull request merged**
